### ISSUE TITLE
Source locator does not exist error for Tomcat launch config

### ISSUE THREAD

**Issue by svdspectral** [ifedorenko/com.ifedorenko.m2e.sourcelookup#20]
Cannot launch Tomcat with eclipse Servers tab with suggested changes:
1 Add <stringAttribute key="org.eclipse.debug.core.source_locator_id" value="com.ifedorenko.m2e.sourcelookupDirector"/> to launch file
2 Add -javaagent:C:\Users\Public\eclipse\plugins\com.ifedorenko.jdt.launching_1.2.0.201704030045\lib\javaagent-shaded.jar
to java options

Values copied from Preferences page

**Comment by ifedorenko** [comment]
I assume this is WTP tomcat server config, right? What is the error message that you get?

**Comment by ifedorenko** [comment]
Should be fixed by dc09a253e1e46d37c89780538d209c36c5f78315. UI got out of sync with the backend when I moved the code from eclipse back to github. Sorry about that.

Note the new configuration is different from the old 1.1.x (not nice, I know):

* `-javaagent:${sourcelookup_javaagent}`
* `<stringAttribute key="org.eclipse.debug.core.source_locator_id" value="com.ifedorenko.jdt.launching.sourceLocator"/>`
